title: Max Siegieda (CampGareth)
email: maxsiegieda@gmail.com
url: "https://www.campgareth.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  CampGareth

# Build settings
remote_theme: sighingnow/jekyll-gitbook
